### ISSUE TITLE
Runtime Disconnected - In the middle of the execution (Google Colab)

### ISSUE THREAD

**Issue by thegamblers** [Nick088Official/FaceFusion-Online-Ports#21]
I've tried running the same Colab notebook using multiple accounts but still it throws that error, within a maximum of 15-25 mins of execution in all of the accounts. What i think is that the issue is related to the GPU usage, i've tested using both the CPU and the GPU, in the case of cpu there is no such issues like disconnection but the process is really slow, while with the case of gpu it disconnects within 10-15 mins.

**Comment by Nick088Official** [comment]
I just updated it, could you retry now? Even on multiple accounts because before this update I tested it myslef, and on an account I got disconnected in 8 mins, while in the other it ran for 30 mins. Let me know if it helps

**Comment by thegamblers** [comment]
I'm still facing the issue, you know @Nick088Official the last version of that same facefusion(2.6.something) which you have uploaded as a colab file doesn't had any such issues, i even have continuously used that for more than 2 hours and still there was no disconnections at all.

**Comment by Nick088Official** [comment]
> I'm still facing the issue, you know @Nick088Official the last version of that same facefusion(2.6.something) which you have uploaded as a colab file doesn't had any such issues, i even have continuously used that for more than 2 hours and still there was no disconnections at all.

Wait what, you now used an older version of my colab and it worked today? Or do you mean that before I updated it had no issues (like a week ago)? 
Because I updated in fact the encryption bc the older version had problems of getting disconnected in like 6 mins, as the new colab detection system it affects it generally.

**Comment by thegamblers** [comment]
Yeah right, before you updated the code to the newer version of colab I wasn't facing any such issues. But now they are quite frequent.

**Comment by Nick088Official** [comment]
> Yeah right, before you updated the code to the newer version of colab I wasn't facing any such issues. But now they are quite frequent.

Yea that’s not related to the fact that I updated it, it’s related that recently google colab updated their detection system (which ofcourse you can’t revert), like if you use the old colab code nothing would change because the detection system is still updated. Meanwhile I try making it more stable those days as with still over 3 layers of encryption it still gets detected,

I can only suggest to retry multiple times with different accounts, and mostly use the lightning.ai port that has nothing against deepfakes & web uis, so you can run that perfectly fine for free.

**Comment by thegamblers** [comment]
If i buy the colab pro subscription, will that fix that issue??

**Comment by Nick088Official** [comment]
> If i buy the colab pro subscription, will that fix that issue??

Google Colab doesn’t allow web uis and deepfakes in the free tier, for sure web uis are allowed in the paid tier, I’m not 100% sure but it should allow deepfakes too but it should fix this all as said in https://www.reddit.com/r/SFWdeepfakes/comments/uzvsbn/comment/ib4x3n5/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button & https://forum.faceswap.dev/viewtopic.php?t=1886&start=20

**Comment by gilroff** [comment]
> If i buy the colab pro subscription, will that fix that issue??

Get a gradient paperspace account. You can run stable diffusion or any image AIs for $8/month. If you can tinker for 10 minutes, I can help you get facefusion running there too.

**Comment by gilroff** [comment]
> > > If i buy the colab pro subscription, will that fix that issue??
> > 
> > 
> > Get a gradient paperspace account. You can run stable diffusion or any image AIs for $8/month. If you can tinker for 10 minutes, I can help you get facefusion running there too.
> 
> Please tell me your telegram/whatsapp or anything over which i can contact you

@thegamblers You can contact me on telegram @didakoo

**Comment by Nick088Official** [comment]
I guess I will close this issue as it will be resolved by using Paperspace.
