### ISSUE TITLE
Lightning AI is Down

### ISSUE THREAD

**Issue by Dragneure** [Nick088Official/FaceFusion-Online-Ports#32]
Lightning AI is down today?

**Comment by Dragneure** [comment]
I guess it got deleted.

**Comment by Nick088Official** [comment]
> I guess it got deleted.

No my notebook is not deleted, It's an issue with lightning.ai.

If you search for any studios it goes blank
And if you pen any published studios in anyone's profile, it redirects to the featured studios just like how it happens when you click the link of my notebook.

It seems an issue with the platform, I already contacted lightning.ai on their Discord and I'm waiting for their response.

Meanwhile, you can either use my other online ports or wait.

**Comment by Dragneure** [comment]
Thx
